spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mazenBD
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  file:
    upload-dir: ../static/uploads
  mail:
    host: smtp.gmail.com
    port: 587
    username: "helasaoudi024@gmail.com"
    password: "jqvb voph nxzr vkmt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

